name: Build project

on: 
  push:
    branches:
      - "main"
env:
  DISTRIBUTIONS: |
    [
      { unityPlatform: "StandaloneWindows64", itchChannel: "win", "runs-on": "windows-2022", "deployToDedicatedRemote": false },
      # { unityPlatform: "StandaloneOSX", itchChannel: "mac", "runs-on": "macos-latest", "deployToDedicatedRemote": false }, NEED APPLE DEVELOPER ACCOUNT
      { unityPlatform: "StandaloneLinux64", itchChannel: "linux", "runs-on": "ubuntu-latest, "deployToDedicatedRemote": false },
      { unityPlatform: "Android", itchChannel: "android", "runs-on": "ubuntu-latest, "deployToDedicatedRemote": false },
      { unityPlatform: "WebGL", itchChannel: "webgl", "runs-on": "ubuntu-latest", "deployToDedicatedRemote": true },
    ]

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          DISTRIBUTIONS='${{  env.DISTRIBUTIONS }}'
          DISTRIBUTIONS=${DISTRIBUTIONS//[$'\t\r\n']}
          echo "matrix=${DISTRIBUTIONS}" >> $GITHUB_OUTPUT
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.array.unityPlatform }}
    needs: [ set-matrix ]
    uses: wisestump/fgj24/.github/workflows/build-platform.yml@main
    strategy:
      fail-fast: false
      matrix:
        array: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
    with: 
      runs-on: ${{ matrix.array.runs-on }}
      unityPlatform: ${{ matrix.array.unityPlatform }}
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  deployAllPlatforms:
    name: Deploy for ${{ matrix.array.unityPlatform }}
    needs: [ set-matrix, buildForAllSupportedPlatforms ]
    uses: wisestump/fgj24/.github/workflows/deploy-platform.yml@main
    with: 
      unityPlatform: ${{ matrix.array.unityPlatform }}
      itchChannel: ${{ matrix.array.itchChannel }}
      deployToDedicatedRemote: ${{ matrix.array.deployToDedicatedRemote }}
    strategy:
      fail-fast: false
      matrix:
        array: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
    secrets:
      BUTLER_API_KEY: ${{ secrets.BUTLE_API_KEY }}
      HOST: ${{ secrets.HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PASSWORD: ${{ secrets.PASSWORD }}
      SSH_USER: ${{ secrets.SSH_USER }}